services:
  mongodb:
      image: mongo:7.0.5
      container_name: mongodb
      ports:
        - "27017:27017"
      environment:
        - MONOGO_INITDB_ROOT_USERNAME=root
        - MONOGO_INITDB_ROOT_PASSWORD=password
        - MONOGO_INITDB_DATABASE=product-service
      volumes:
        - ./data:/data/db